### ISSUE TITLE
Cross Building for Scala 2.12

### ISSUE THREAD

**Issue by 2chilled** [tek/kallikrein#1]
We just wanted to try out kallikrein for a fresh small project at work but unfortunately our Scala universe is still on 2.12. I think it would be beneficial to have a cross build setup. WDYT?

**Comment by tek** [comment]
Last time I tried there were some issues with the 2.12 typechecker, but I can give it another look!

**Comment by tek** [comment]
wasn't that hard. making a release now! please be aware that `ForAll`might exhibit a bug when you use the library with newer versions of `fs2` or `cats-effect`. I just noticed that and will investigate.

**Comment by tek** [comment]
@2chilled please let me know what you think about the lib after evaluation!
